### PR TITLE
Some more Xenonauten clothing and placeholder Jaeger exoskeleton helmets.

### PR DESCRIPTION
**Pull request by PetMudstone**
### Purpose
- Adds more variants of the Xenonauten-M pattern vest. Flak jacket, Xenonauten-L and Xenonauten-H.
- Adds the M10XE and M11X variants of the M10X helmet.
- Adds in placeholder Jaeger helmets, _ModularSuitBaseCM changed into Jaeger exoskeleton.

### Notes:
The Jaeger exoskeleton and ESPECIALLY helmets are just placeholders. There is no attachment system in place and the helmets don't even have sprites due to how Jaeger helmet sprites are set up, being a collection of various overlays with variable coloration.

### Changelog:

CL: [New] Added TerraGov flak jacket, Xenonauten-L and Xenonauten-H pattern vests, and added M10XE and M11X pattern helmets.

### CODE REVIEW

**Comment by MaxIsJoe** [comment]
tests are failing

**Comment by PetMudstone** [comment]
image
All test failures are due to things not touched by this PR.

**Comment by MaxIsJoe** [comment]
that's odd

**Comment by MaxIsJoe** [comment]
can you post me the errors all of these give

**Comment by PetMudstone** [comment]
### CargoOrdersHaveACrate
image
image


### StonksTest
image

### APCPoweredDevicesHaveRelatedAPC (Teststation)
image

**Pull request merged**
